config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :users
  resources :reports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  attachment :image
  
  with_options presence: true do
    validates :title
    validates :body
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :reports, dependent: :destroy
  
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  def index
    @reports = Report.order(id: :desc)
  end

  def show
    @report = Report.find(params[:id])
  end

  def new
    @report = Report.new
  end
  
  def create
    @report = Report.new(report_params)
    @report.user_id = current_user.id 
    if @report.save
      redirect_to reports_path(@user)
    else
      render :new
    end
  end

  def edit
    @report = Report.find(params[:id])
    if @report.user != current_user
      redirect_to reports_path, alert: '不正なアクセスです'
    end
  end
  
  def update
    @report = Report.find(params[:id])
    @report.user_id = current_user.id
    if @report.update(report_params)
     redirect_to report_path(@report), notice: '更新しました。'
   else
     render :edit
    end
  end
  
  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    redirect_to reports_path, notice: '削除しました。'
  end
  
  private
  
  def report_params
    params.require(:report).permit(:title, :body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! #ログインしていないと制限される。
  def index
    @users = User.order(id: :desc)
  end

  def show
    @user = User.find(params[:id])
    @reports = @user.reports.order(report_id: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path, alert: '不正なアクセスです'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '更新しました'
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="center jumbotron">
  <div class="container">
  <div class="text-center">
    <figure>
      <div class="main-image"></div>
    </figure>
  </div>
</div>
  <div class="text-center">
    <%= link_to '新規登録画面', new_user_registration_path, class: 'btn btn-lg btn-primary' %>
    <%= link_to 'ログイン画面', new_user_session_path, class: 'btn btn-lg btn-success' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DayserviceApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <% if flash[:notice] %>
   <div class="alert alert-info" role="alert">
     <p class="notice"><%= notice %></p>
   </div>
 <% end %>
   
 <% if flash[:alert] %>
   <div class="alert alert-danger" role="alert">
     <p class="alert"><%= alert %></p>
   </div>
 <% end %>
 
 <header class="mb-4">
 <nav class="navbar navbar-expand navbar-dark bg-info">
   <h1 style="font-family: cursive"><a class="navbar-brand" href="/">Sakuraデイサービス</a></h1>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
     <span class="navbar-toggle-icon"></span>
   </button>
   
   <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
     <ul class="navbar-nav">
      <% if user_signed_in? %>
       <li class="nav-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
       <li class="nav-item"><%= link_to 'マイページ', user_path(current_user), class: 'nav-link' %></li>
       <li class="nav-item"><%= link_to '利用者一覧', users_path, class: 'nav-link' %></li>
       <li class="nav-item"><%= link_to '連絡帳一覧画面', reports_path, class: 'nav-link' %></li>
       <li class="nav-item"><%= link_to '連絡帳新規投稿', new_report_path, class: 'nav-link' %></li>
     <% else %>    
       
       <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %></li>
       <li class="nav-item"><%= link_to '新規ユーザー登録', new_user_registration_path, class: 'nav-link' %></li>
     <% end %>
     </ul>
   </div>
 </nav>
</header>
    <%= yield %>
  </body>
</html>

app/views/reports/edit.html.erb
<div class="text-center mb-4">
  <h2><%= @report.user.username %>様</h2>
  <h3><%= @report.created_at.strftime("%Y年%m月%d日") %>の出来事</h3>
</div> 

<% if @report.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@report.errors.count, "error") %></h2>
   <ul>
     <% @report.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>


<div class="row mt-4 pt-4">
  <div class="offset-sm-3 col-sm-6">    
    <%= form_for @report do |f| %>
     
     <div class="form-group">
      <%= f.label :tilte, '要件' %>
      <%= f.text_field :title, class: "form-control input" %>
     </div>
     
     <div class="form-group">
      <%= f.label :body, "特記事項" %>
      <%= f.text_area :body, class: "form-control text-area" %>
     </div>        
      
     <div class="form-group">
      <%= f.label :image, "写真" %>
      <%= f.attachment_field :image, class: "form-control input" %>
     </div>
      
    <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

  

app/views/reports/index.html.erb
<div class="base-container mw-xl">
<div class="texts-wrapper">
  <div class="contents-title text-center">
   <% @reports.each do |report| %>
    <h2 style="font-family: Hiragino Mincho ProN">
      <%= link_to report_path(report) do %>
        <%= report.created_at.strftime("%Y年%m月%d日") %>の出来事<!-- config/application.rb に　「config.tim_zone = 'Tokyo'」を記述する -->
      <% end %>
    </h2>
    <div class="content-wrapper ml-5 pl-5">
      <div class="row">
          <div class="col-sm-5">
            <div class="card">
              <div class="card-header">
                <%= link_to user_path(report.user.id) do %><!-- reportに紐づいた user.id -->
                 <%= attachment_image_tag report.user, :profile_image, :size => "160x160", fallback: 'no-image.png' %>
                <% end %>
              </div>
              <div class="card-body">
                <%= link_to user_path(report.user.id) do %><!-- report に紐づいた user.id -->
                  <h3><%= report.user.username %>の詳細情報<!-- report に紐づいた username --></h3>
                <% end %>
              </div>
            </div>
          </div>
           
          <div class="col-sm-5">
            <div class="card">
              <div class="card-header">
                <%= link_to report_path(report) do %>
                 <%= attachment_image_tag report, :image, :size => "160x160" %>
                <% end %>
              </div>
              <div class="card-body">
                <p><%= report.title %></p>
                <p><%= report.body %></p>
              </div>
            </div>
          </div>
      </div>
    </div>
   <% end %>
  </div>
</div>
</div>

app/views/reports/new.html.erb
<div class="text-center mb-4">
  <h3><%= Date.current.strftime("%Y年%m月%d日") %>の出来事</h3>
</div> 

<% if @report.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@report.errors.count, "error") %></h2>
   <ul>
     <% @report.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

<div class="row mt-4 pt-4">
  <div class="offset-sm-3 col-sm-6">    
    <%= form_for @report do |f| %>
     
     <div class="form-group">
      <%= f.label :tilte, '要件' %>
      <%= f.text_field :title, class: "form-control" %>
     </div>
     
     <div class="form-group">
      <%= f.label :body, "特記事項" %>
      <%= f.text_area :body, class: "form-control" %>
     </div>        
      
     <div class="form-group">
      <%= f.label :image, "写真" %>
      <%= f.attachment_field :image, class: "form-control" %>
     </div>
      
    <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/reports/show.html.erb
<div class="base-container mw-xl">
<div class="texts-wrapper">
  <div class="contents-title text-center">
    <h2 style="font-family: Hiragino Mincho ProN"><%= @report.created_at.strftime("%Y年%m月%d日") %> のご本人様の様子</h2>
    <br>
    <br>
    
      <div class="row justify-content-center">
        
          <div class="col-sm-4 card">
            <div class="card-header">
              <%= attachment_image_tag @report, :image, :size => "160x160", fallback: "no-image.png" %>
            </div>
            
          </div>
          
        <div class="co-sm-6">
          <div class="card-body">
              <p><%= @report.title %></p>
              
              <div>
                <p><%= simple_format @report.body %></p>
              </div>
              <div>
                <% if @report.user.id == current_user.id %>
                   <!-- ユーザーモデルのユーザ名に紐づいたレポートのインスタンス変数 -->
                  <%= link_to "編集", edit_report_path(@report), class: 'btn btn-success' %>
                <% end %>
              </div>
            </div>
         <%= link_to user_path(@report.user) do %>
           <%= @report.user.username %> さんのページへ
         <% end %>
        </div>
      </div>
      
  </div>
</div>
</div>

app/views/users/edit.html.erb
  <div class="text-center mb-4">
    <h2>利用者情報編集画面</h2>
   </div> 
   
   <% if @user.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(@user.errors.count, "error") %></h2>
   <ul>
     <% @user.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

<div class="row mt-4 pt-4">
  <div class="offset-sm-3 col-sm-6">
    <%= form_for @user do |f| %>
    
    <div class="form-group">
     <%= f.label :お名前 %>
     <%= f.text_field :username, class: 'form-control' %>
    </div>
    
    <div class="form-group">
     <%= f.label :Eメール %>
     <%= f.email_field :email, class: 'form-control' %>
    </div>
    
    <div class="form-group">
     <%= f.label :利用者詳細情報 %>
     <%= f.text_area :profile, class: 'form-control' %>
    </div>
    
    <div class="form-group">
     <%= f.label :プロフィール写真 %>
     <%= f.attachment_field :profile_image, class: 'form-control' %>
    </div>
    
    <%= f.submit '変更', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>    
    

app/views/users/index.html.erb
<div class="base-container mw-xl">
<div class="texts-wrapper">
  <div class="contents-title text-center">
    <h2 style="font-family: Hiragino Mincho ProN">利用者一覧</h2>
    
      <div class="row">
        <% @users.each do |user| %>
          <div class="col-sm-5">
            <div class="card">
              <%=link_to  user_path(user) do %>
                <%= attachment_image_tag user, :profile_image, :size => "520x520", fallback: "no-image.png" %>
              <% end %>
              <h3 class="text-left ml-5">
                <%= link_to user_path(user) do %>
                 <%= user.username %>
                <% end %>
              </h3>
              <p class="text-left ml-5">投稿数：　　</p>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="base-container mw-xl">
<div class="texts-wrapper">
  <div class="contents-title text-center">
    <h2 style="font-family: Hiragino Mincho ProN">利用者詳細情報</h2>
    <br>
    <br>
    
      <div class="row justify-content-center">
        
          <div class="col-xl-4 card">
            <div class="card-header">
              <%= attachment_image_tag @user, :profile_image, :size => "320x320", fallback: "no-image.png" %>
            </div>
            <div class="card-body">
              <h3><%= @user.username %></h3>
              <% if @user.id == current_user.id %>
              <p><%= @user.email %></p>
              <p><%= link_to '編集', edit_user_path(@user), class: 'btn btn-primary' %></p>
              <% end %>
              <div>
                <p><%= simple_format @user.profile %></p>
              </div>
            </div>
          </div>
      </div>
      
      <div class="row justify-content-center">
          <div class="col-xl-4 card">
           <% @user.reports.each do |report| %>
            <div class="card-header">
              <h2><%= report.created_at.strftime("%Y年%m月%d日") %>の様子</h2>
              <%= link_to report_path(report) do %>
               <%= attachment_image_tag report, :image, :size => "320x320", fallback: "no-image.png" %>
              <% end %>
            </div>
            <div class="card-body">
             <% if @user.id == current_user.id %>
              <p><%= link_to report_path(report) do %>
                    <span class="panel-icon">
                      <i class="fas fa-book"></i>
                    </span>
                    この日の連絡帳を見る
                  <% end %>
              </p>
              <% if @user.id == current_user.id %>
              <p><%= link_to edit_report_path(report), data: {confirm: "編集しますか?"} do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この連絡帳を編集する
              <% end %>
              </p>
              
              <p><%= link_to report_path(report), method: :delete, data: {confirm: "削除しますか？"} do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この日の連絡帳を削除する
              <% end %>
              </p>
              <% end %>
             <% end %>
            </div>
           <% end %>
          </div>
      </div>
      
  </div>
</div>
</div>


 